# -*- coding: utf-8 -*-
"""62994401364_lista_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17rCnXruoyeYL8F6YBej7KjpIdD_6HiLV

![WhatsApp%20Image%202023-09-10%20at%2011.20.28.jpeg](attachment:WhatsApp%20Image%202023-09-10%20at%2011.20.28.jpeg)

### Fala devs, blz??

Esta será nossa primeira lista de exercícios para você testar seu conhecimento acerca do conteúdo do MÓDULO 2:

-Meu Primeiro Programa em Python


-Estrutura de Dados

## INSTRUÇÕES:

A lista deve ser realizada pelo Jupyter Notebook.

Nâo é necessário entregar a lista para afins de certificado dentro da plataforma, entretanto para alunos da USP que queiram participar do processo seletivo ou conseguir créditos AAC (apenas FEANOS) é necessária a entrega de TODAS as listas.

A entrega das listas ou pelo menos sua excecução é recomendada a fim de exercitar todo o conhecimento adquirido do curso.

O DESAFIO é para realmente te desafiar, por isso não desista de tentar e de continuar com o curso, ao longo das listas você verá que cada vez mais você terá ferramentas para completá-lo.

Caso haja alguma dúvida acerca da lista participe das monitorias que serão oferecidas as quintas e sábados das 17h as 18h pelo DISCORD. Caso seu problema não seje resolvido envie uma mensagem para contato.feadev@gmail.com

O gabarito será disponibilizado na plataforma após o término de periodo de envio
"""

## vamos começar??

"""## QUESTÃO 0

Todo programador deve saber apenas uma coisa: Pedir para o Python escrever "Hello, Word"
Vamos testar se você já pode ser nomeado como um programador???
"""

print("Hello, World!")

"""E se eu te pedir para criar um código que tenha como OUTPUT  (termo comumente usado na programação e na computação em geral para se referir à saída de um programa ou processo) o seu número favorito? Como seria?"""

print("Meu número favorito é:", 13)

"""## QUESTÃO 1

Você está fazendo um pedido no Starbucks e na hora da compra pedem o seu nome completo para te chamarem quando seu pedido estiver pronto. Entretanto a moça do caixa anota somente o seu primeiro nome. Só depois de ter visto que haviam muitas pessoas na fila com o mesmo nome que o seu, ela te pergunta somente o seu sobrenome.

Na hora de entrega do seu pedido, como o atendente chamará por você??

Agora, sua tarefa é criar um código em Python no Jupyter Notebook para combinar o seu primeiro nome e seu sobrenome e exibir o nome completo que o atendente usará para chamar você quando seu pedido estiver pronto.

Seu código deve fazer o seguinte:

Declare duas variáveis: primeiro_nome e sobrenome.
Atribua um valor ao primeiro_nome representando o primeiro nome que a atendente anotou.
Atribua um valor ao sobrenome representando o sobrenome que a atendente solicitou posteriormente.
Use sua habilidade em Python para combinar essas duas partes e criar o nome completo.
Exiba o nome completo no Jupyter Notebook.

Desafio aceito? Agora, você está pronto para criar o código que garantirá que o atendente do Starbucks chame você corretamente quando seu pedido estiver pronto! ☕🪄

![Captura%20de%20tela%202023-09-24%20140330.png](attachment:Captura%20de%20tela%202023-09-24%20140330.png)
"""

primeiro_nome = "Jefferson"
sobrenome = "Melo"
nome_completo = primeiro_nome + " " + sobrenome
print("Nome completo para chamar no Starbucks:", nome_completo)

"""## QUESTÃO 2

Imagine que você é um professor de Matemática para crianças do ensino fundamental e um aluno curioso te pergunta:

"Professor, quanto é 13 + 15 + 16 + 6?"

Você, é claro, não quer parecer contar nos dedos por baixo da mesa para uma pergunta tão simples. Então, você decide mostrar toda a sua sabedoria tecnológica e recorre ao Python para dar a resposta instantaneamente.

Como deve ser o código para chegar ao resultado?

![Captura%20de%20tela%202023-09-24%20140141.png](attachment:Captura%20de%20tela%202023-09-24%20140141.png)
"""

# Declare as variáveis com os números a serem somados:
numero1 = 13
numero2 = 15
numero3 = 16
numero4 = 6

# Realize a soma dos números:
soma = numero1 + numero2 + numero3 + numero4

# Exiba o resultado:
print("A soma é:", soma)

"""## QUESTÃO 3

Você é um detetive de palavras, conhecido por desvendar enigmas usando manipulação de texto. Hoje, você enfrenta um novo mistério envolvendo uma mensagem secreta. Sua missão é decifrar essa mensagem usando operações com texto em Python.

Mistério da Mensagem Secreta:

Você recebeu a seguinte mensagem secreta:
"""

#Mistério: @s4b@d0 3n0c0nd3 3st@ m3n$@g3m. P0d3r14$ d3c1fr@-l@?

"""A mensagem parece confusa, mas você sabe que ela contém informações importantes. Aqui estão as etapas que você deve seguir para decifrar a mensagem:

Crie uma variável chamada mensagem e atribua a ela a mensagem secreta fornecida acima.
Use operações de texto em Python para limpar a mensagem, removendo todos os caracteres especiais, números e espaços em branco.

Converta a mensagem resultante para letras minúsculas.

Agora que a mensagem está limpa, você pode decifrá-la? A mensagem secreta pode conter uma pista importante!

Crie um código em Python no Jupyter Notebook para realizar essas etapas e revelar o que está por trás desse mistério! 🕵️‍♂️🔍
"""

# Mensagem secreta fornecida
mensagem = "#Mistério: @s4b@d0 3n0c0nd3 3st@ m3n$@g3m. P0d3r14$ d3c1fr@-l@?"

# Remover caracteres especiais, números e espaços em branco usando replace() várias vezes
mensagem_limpa = mensagem.replace("#", "").replace("@", "").replace("4", "").replace("0", "").replace("3", "").replace("$", "").replace("-", "").replace(" ", "")

# Converter para letras minúsculas
mensagem_limpa = mensagem_limpa.lower()

# Exibir a mensagem limpa
print("Mensagem limpa:", mensagem_limpa)

"""## QUESTÃO 4

Você acaba de ingressar no curso de Python do FEA.dev e decide iniciar sua própria consultoria. Parabéns!!! Você logo recebe seu primeiro cliente, a pizzaria do bairro. Ela tem um grande objetivo em mente: desbancar a grande indústria de pizza Baralho's e Pizza Wut. Para isso, vai recorrer à tecnologia em seus processos.

Sua primeira função é criar um sistema que recebe o valor de cada venda de pizza e bebida e imprima o valor final.
"""

# Função para calcular o valor total da venda
def calcular_valor_venda(pizza, bebida):
    # Preço das pizzas e bebidas
    preco_pizza = 10  # Preço de cada pizza
    preco_bebida = 3  # Preço de cada bebida

    # Calcular o valor total da venda
    total_venda = (pizza * preco_pizza) + (bebida * preco_bebida)

    return total_venda

# Solicitar a quantidade de pizzas e bebidas vendidas
quantidade_pizzas = int(input("Quantidade de pizzas vendidas: "))
quantidade_bebidas = int(input("Quantidade de bebidas vendidas: "))

# Calcular o valor total da venda
valor_total = calcular_valor_venda(quantidade_pizzas, quantidade_bebidas)

# Exibir o valor total da venda
print("Valor total da venda: R$", valor_total)

"""![pizza_batepapo.webp](attachment:pizza_batepapo.webp)

## QUESTÃO 5

Excelente! A clientela adorou o programa de fidelidade.
Feito isto, chegou a hora de olhar para os processos internos. A ideia é automatizar a lista de compra da semana, antes feita no papel.

a) O chef de cozinha resolveu aprender uma receita que utiliza a fermentação natural, de forma que a pizza fique mais próxima da tradicional italiana. Feito isso, não há mais necessidade de utilizar leite, ovos e fermento biológico para a receita. Retire-os da lista de compras e em seguida, adicione Levain e Açúcar, ingredientes da fermentação natural. Imprima a nova lista.
"""

compras = ['Farinha de Trigo', 'Ovos', 'Fermento Biológico', 'Leite', 'Calabresa', 'Milho',
           'Champignon', 'Molho de Tomate', 'Frango', 'Requeijão', 'Lombo']

# Lista de compras original
compras = ['Farinha de Trigo', 'Ovos', 'Fermento Biológico', 'Leite', 'Calabresa', 'Milho', 'Champignon', 'Molho de Tomate', 'Frango', 'Requeijão', 'Lombo']

# Ingredientes a serem removidos
ingredientes_remover = ['Ovos', 'Fermento Biológico', 'Leite']

# Ingredientes a serem adicionados
ingredientes_adicionar = ['Levain', 'Açúcar']

# Remover ingredientes da lista de compras
for ingrediente in ingredientes_remover:
    if ingrediente in compras:
        compras.remove(ingrediente)

# Adicionar ingredientes à lista de compras
compras.extend(ingredientes_adicionar)

# Imprimir a nova lista de compras
print("Nova lista de compras:", compras)

"""b) Enquanto você estava com o computador ligado, um hacker da pizzaria rival do bairro resolveu atacar sua lista de compras invertendo alguns dos itens, como se vê abaixo:

![Captura%20de%20tela%202023-09-24%20135736.png](attachment:Captura%20de%20tela%202023-09-24%20135736.png)

Conserte os valores que foram adulterados e imprima a lista corrigida.
"""

# Lista invertida pelo hacker
sarpmoc = ['ogirT ed ahniraF', 'Calabresa', 'Milho', 'Champignon', 'etamoT ed ohloM', 'Frango',
           'Requeijão', 'Lombo', 'niaveL', 'Açúcar']

# Inverter a lista para restaurar a ordem original
sarpmoc.reverse()

# Imprimir a lista restaurada
print("Lista de compras restaurada:", sarpmoc)

"""c) Após esse duro golpe, você percebe que é necessário guardar as informações importantes em uma estrutura de dados que seja mais segura (isto é, que não seja mutável). Converta a lista de compras para uma estrutura com estas características e imprima o tipo da variável. &nbsp; Dica: Utilize a função type() para obter o tipo da variável"""

# Lista de compras original
compras = ['Farinha de Trigo', 'Calabresa', 'Milho', 'Champignon', 'Molho de Tomate', 'Frango', 'Requeijão', 'Lombo', 'Levain', 'Açúcar']

# Converter a lista de compras em uma tupla
compras_tupla = tuple(compras)

# Imprimir o tipo da variável
print("Tipo da variável compras_tupla:", type(compras_tupla))

"""![af5addc01d02cc4bc54fd86a456e3dce90d2e4276b59c876cea22cc84e9a4f07_1.jpg](attachment:af5addc01d02cc4bc54fd86a456e3dce90d2e4276b59c876cea22cc84e9a4f07_1.jpg)

## QUESTÃO 6

Empresas modernas se importam com ESG (Environmental, Social and Governance). A pizzaria do bairro não seria diferente, e sua missão é auxiliar a empresa a reduzir as emissões de lixo em sua operação. &nbsp;

![ac137a44f5f8cd3c6126fc8ff8c24fff.jpg](attachment:ac137a44f5f8cd3c6126fc8ff8c24fff.jpg)

O primeiro passo será tornar o panfleto digital, de forma que seja enviado pelas redes sociais e não precise ser impresso e consequentemente descartável. Para demonstrar essa funcionalidade ao dono, você deve criar um exemplo de panfleto que contenha os sabores de pizza salgadas e doces (separados), tipos de bebida e adicionais, conforme os valores a seguir:
-  Pizzas salgadas: Calabresa, Portuguesa, Mussarela e Pepperoni;
-  Pizzas doces: Prestígio, Chocolate e Doce de Leite;
-  Bebidas: Guaraná, Cola, Suco de Laranja e Suco de Uva;
-  Adicionais: Bacon, Requeijão, Milho e Azeitona

Imprima o panfleto final.
"""

# Pizzas salgadas
pizzas_salgadas = ["Calabresa", "Portuguesa", "Mussarela", "Pepperoni"]

# Pizzas doces
pizzas_doces = ["Prestígio", "Chocolate", "Doce de Leite"]

# Bebidas
bebidas = ["Guaraná", "Cola", "Suco de Laranja", "Suco de Uva"]

# Adicionais
adicionais = ["Bacon", "Requeijão", "Milho", "Azeitona"]

# Imprimir o panfleto
print("Panfleto Digital - Pizzaria do Bairro\n")

print("Sabores de Pizza Salgadas:")
for sabor in pizzas_salgadas:
    print(f"- {sabor}")

print("\nSabores de Pizza Doces:")
for sabor in pizzas_doces:
    print(f"- {sabor}")

print("\nTipos de Bebida:")
for bebida in bebidas:
    print(f"- {bebida}")

print("\nAdicionais:")
for adicional in adicionais:
    print(f"- {adicional}")

"""### DESAFIO

Sucesso! A pizzaria do bairro tornou-se uma multinacional que engoliu todas as concorrentes. Querendo crescer ainda mais, o dono sugere um novo recurso: criar sua própria pizza. Para isso, temos um dicionário com todos os ingredientes e seus respectivos preços. A pizzaria recebeu os seguintes pedidos:
-  1: Massa sem glúten, molho barbecue, frango, pimentão e tomate
-  2: Massa tradicional, molho de tomate, atum, mussarela, azeitona, cebola, pimentão, tomate e borda com queijo
-  3: Massa integral, molho bechamel, cebola, pimentão, tomate, frango e borda com requeijão

Imprima uma lista com todos os itens do pedido e seu preço final que será retornado ao cliente. Armazene o valor das vendas de forma que não seja possível alterar seus valores e imprima.

![8y2cc1flxem91.jpg](attachment:8y2cc1flxem91.jpg)
"""

# Dicionário de preços dos ingredientes
precos_ingredientes = {
    "Massa sem glúten": 5.0,
    "Massa tradicional": 4.0,
    "Massa integral": 4.5,
    "Molho barbecue": 2.0,
    "Molho de tomate": 1.5,
    "Atum": 3.0,
    "Mussarela": 2.5,
    "Azeitona": 1.0,
    "Cebola": 1.0,
    "Pimentão": 1.0,
    "Tomate": 1.0,
    "Borda com queijo": 2.0,
    "Borda com requeijão": 2.5,
    "Frango": 3.0,
    "Molho bechamel": 2.0
}

# Pedidos e seus ingredientes
pedidos = {
    1: ["Massa sem glúten", "Molho barbecue", "Frango", "Pimentão", "Tomate"],
    2: ["Massa tradicional", "Molho de tomate", "Atum", "Mussarela", "Azeitona", "Cebola", "Pimentão", "Tomate", "Borda com queijo"],
    3: ["Massa integral", "Molho bechamel", "Cebola", "Pimentão", "Tomate", "Frango", "Borda com requeijão"]
}

# Calcular o preço total de cada pedido
preco_vendas = {}

for pedido, ingredientes in pedidos.items():
    preco_total = sum([precos_ingredientes[ingrediente] for ingrediente in ingredientes])
    preco_vendas[pedido] = preco_total

# Imprimir os itens do pedido e seus preços finais
for pedido, ingredientes in pedidos.items():
    print(f"Pedido {pedido}:")
    for ingrediente in ingredientes:
        print(f"- {ingrediente}: R$ {precos_ingredientes[ingrediente]:.2f}")
    print(f"Preço total: R$ {preco_vendas[pedido]:.2f}")
    print()

# Imprimir o valor total das vendas
valor_total_vendas = sum(preco_vendas.values())
print(f"Valor total das vendas: R$ {valor_total_vendas:.2f}")